#!/usr/bin/env bash
# Configure Ollama keep-alive / parallelism and restart the local serve.
# Run on the GPU host that runs `ollama serve` (not inside the auth-proxy container).
set -euo pipefail

KEEP_ALIVE="${OLLAMA_KEEP_ALIVE:-30m}"
NUM_PARALLEL="${OLLAMA_NUM_PARALLEL:-1}"
DROP_IN_DIR="${OLLAMA_SYSTEMD_DROPIN_DIR:-/etc/systemd/system/ollama.service.d}"
WRITE_ENV_FILE="${OLLAMA_ENV_FILE:-}"
RESTART=1
DRY_RUN=0

usage() {
  cat <<'EOF'
Usage: ./configure-ollama.sh [options]

Sets Ollama server env and restarts the service (or prints env for manual serve).

Options:
  --keep-alive VALUE     Idle unload TTL (default: 30m). Use -1 to never unload.
  --num-parallel N       Max parallel model requests (default: 1).
  --env-file PATH        Also write KEY=VALUE lines to PATH (e.g. ~/.config/ollama/env).
  --no-restart           Only write config; do not systemctl restart.
  --dry-run              Print actions only.
  -h, --help             Show this help.

Examples:
  ./configure-ollama.sh
  ./configure-ollama.sh --keep-alive -1 --num-parallel 1
  ./configure-ollama.sh --keep-alive 30m --num-parallel 2 --env-file ~/.ollama-serve.env
  OLLAMA_KEEP_ALIVE=-1 OLLAMA_NUM_PARALLEL=1 ./configure-ollama.sh
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --keep-alive)
      KEEP_ALIVE="${2:?--keep-alive needs a value}"
      shift 2
      ;;
    --num-parallel)
      NUM_PARALLEL="${2:?--num-parallel needs a value}"
      shift 2
      ;;
    --env-file)
      WRITE_ENV_FILE="${2:?--env-file needs a path}"
      shift 2
      ;;
    --no-restart)
      RESTART=0
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if ! [[ "$NUM_PARALLEL" =~ ^[1-9][0-9]*$ ]]; then
  echo "error: --num-parallel must be a positive integer (got: $NUM_PARALLEL)" >&2
  exit 1
fi

run() {
  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "+ $*"
  else
    "$@"
  fi
}

echo "OLLAMA_KEEP_ALIVE=$KEEP_ALIVE"
echo "OLLAMA_NUM_PARALLEL=$NUM_PARALLEL"

# Optional plain env file (source before `ollama serve`, or point systemd at it).
if [[ -n "$WRITE_ENV_FILE" ]]; then
  echo "Writing $WRITE_ENV_FILE"
  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "+ cat > $WRITE_ENV_FILE"
  else
    mkdir -p "$(dirname "$WRITE_ENV_FILE")"
    cat >"$WRITE_ENV_FILE" <<EOF
# Generated by ollama-auth-proxy/configure-ollama.sh
OLLAMA_KEEP_ALIVE=$KEEP_ALIVE
OLLAMA_NUM_PARALLEL=$NUM_PARALLEL
EOF
  fi
fi

# systemd drop-in when ollama.service exists (official Linux install).
if systemctl cat ollama.service >/dev/null 2>&1; then
  DROP_IN="$DROP_IN_DIR/blob-tuning.conf"
  echo "Writing systemd drop-in $DROP_IN (needs sudo if not root)"
  BODY=$(cat <<EOF
[Service]
Environment=OLLAMA_KEEP_ALIVE=$KEEP_ALIVE
Environment=OLLAMA_NUM_PARALLEL=$NUM_PARALLEL
EOF
)
  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "+ sudo tee $DROP_IN <<EOF"
    echo "$BODY"
    echo "EOF"
    echo "+ sudo systemctl daemon-reload"
    [[ "$RESTART" -eq 1 ]] && echo "+ sudo systemctl restart ollama"
  else
    if [[ "$(id -u)" -eq 0 ]]; then
      mkdir -p "$DROP_IN_DIR"
      printf '%s\n' "$BODY" >"$DROP_IN"
      systemctl daemon-reload
      [[ "$RESTART" -eq 1 ]] && systemctl restart ollama
    else
      sudo mkdir -p "$DROP_IN_DIR"
      printf '%s\n' "$BODY" | sudo tee "$DROP_IN" >/dev/null
      sudo systemctl daemon-reload
      [[ "$RESTART" -eq 1 ]] && sudo systemctl restart ollama
    fi
    echo "ollama.service updated."
    systemctl show ollama.service -p Environment --no-pager 2>/dev/null || true
  fi
else
  echo "No systemd unit 'ollama.service' found."
  echo "For a manual serve, export then restart:"
  echo "  export OLLAMA_KEEP_ALIVE=$KEEP_ALIVE"
  echo "  export OLLAMA_NUM_PARALLEL=$NUM_PARALLEL"
  echo "  # kill existing ollama serve, then:"
  echo "  ollama serve"
  if [[ "$RESTART" -eq 1 && -n "$(pgrep -x ollama || true)" ]]; then
    echo "Detected running ollama process(es). Restart manually after exporting env."
  fi
fi

echo "Done."
